import type { Metadata } from "next";

import "./globals.css";
import NaveBarGen from "@/components/ui/navbar";
import ContactInfo from "@/sections/contactInfo";
// export const metadata: Metadata = {
//   title: "الأستاذ",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  title: "الأستاذ",
  description: "موقع الأستاذ يقدم تسهيلا لإنجاز الوثائق التربوية كالتوازبع والمعلقات ....",
  keywords: ["تعليم", "دروس", "الأستاذ", "تعليم إلكتروني", "التوازبع", "المعلقات"],
  authors: [{ name: "عز الدين عويسي" }],
  openGraph: {
    title: "الأستاذ",
    description: "أنجز وثائقك بسهولة.",
    url: "https://teacher-sage.vercel.app/",
    siteName: "الأستاذ",
    images: [
      {
        url: "https://teacher-sage.vercel.app/_next/image?url=%2Fimages%2Fteacher.jpg&w=1920&q=75",
        width: 800,
        height: 600,
      },
    ],
    locale: "ar_AR",
    type: "website",
  },
  alternates: {
    canonical: "https://teacher-sage.vercel.app/",
  },
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
      <body
        // className={`${cairo.variable} ${tajawal.variable} ${almarai.variable} ${changa.variable} ${amiri.variable} ${harmattan.variable} ${ibmPlexSansArabic.variable} ${notoSansArabic.variable} ${rubik.variable} antialiased container mx-auto px-4 sm:px-6 lg:px-8 pt-3`}
      className="antialiased flex flex-col min-h-screen container mx-auto px-4 sm:px-6 lg:px-8 pt-3"
      >
        <NaveBarGen />
        {children}
      </body>
      <footer className="mt-10 mb-5 flex justify-center items-center">
        <h2 className="ml-2 text-2xl">للتواصل :</h2>
      <ContactInfo />
      </footer>
    </html>
  );
}
