import type { Metadata } from "next";
// import {
//   Cairo,
//   Tajawal,
//   Almarai,
//   Changa,
//   Amiri,
//   Harmattan,
//   IBM_Plex_Sans_Arabic,
//   Noto_Sans_Arabic,
//   Rubik,
// } from "next/font/google";
import "./globals.css";
import NaveBarGen from "@/components/ui/navbar";

// const cairo = Cairo({
//   subsets: ["arabic"],
//   display: "swap",
//   variable: "--font-cairo",
// });

// const tajawal = Tajawal({
//   weight: ["400", "500", "700"],
//   subsets: ["arabic"],
//   display: "swap",
//   variable: "--font-tajawal",
// });

// const almarai = Almarai({
//   weight: ["400", "700"],
//   subsets: ["arabic"],
//   display: "swap",
//   variable: "--font-almarai",
// });

// const changa = Changa({
//   weight: ["400", "700"],
//   subsets: ["arabic"],
//   display: "swap",
//   variable: "--font-changa",
// });

// const amiri = Amiri({
//   weight: ["400", "700"],
//   subsets: ["arabic"],
//   display: "swap",
//   variable: "--font-amiri",
// });

// const harmattan = Harmattan({
//   weight: ["400", "700"],
//   subsets: ["arabic"],
//   display: "swap",
//   variable: "--font-harmattan",
// });

// const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
//   weight: ["400", "500", "600", "700"],
//   subsets: ["arabic"],
//   display: "swap",
//   variable: "--font-ibm-plex-sans-arabic",
// });

// const notoSansArabic = Noto_Sans_Arabic({
//   weight: ["400", "500", "700"],
//   subsets: ["arabic"],
//   display: "swap",
//   variable: "--font-noto-sans-arabic",
// });

// const rubik = Rubik({
//   weight: ["400", "500", "700"],
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-rubik",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
      <body
        // className={`${cairo.variable} ${tajawal.variable} ${almarai.variable} ${changa.variable} ${amiri.variable} ${harmattan.variable} ${ibmPlexSansArabic.variable} ${notoSansArabic.variable} ${rubik.variable} antialiased container mx-auto px-4 sm:px-6 lg:px-8 pt-3`}
        className={`antialiased container mx-auto px-4 sm:px-6 lg:px-8 pt-3`}
      >
        <NaveBarGen />
        {children}
      </body>
    </html>
  );
}
